// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed GUIa2C.png
var resourceGUIa2CPngData []byte
var resourceGUIa2CPng = &fyne.StaticResource{
	StaticName:    "GUIa2C.png",
	StaticContent: resourceGUIa2CPngData,
}

//go:embed GUIa3.png
var resourceGUIa3PngData []byte
var resourceGUIa3Png = &fyne.StaticResource{
	StaticName:    "GUIa3.png",
	StaticContent: resourceGUIa3PngData,
}

//go:embed GUIf2.png
var resourceGUIf2PngData []byte
var resourceGUIf2Png = &fyne.StaticResource{
	StaticName:    "GUIf2.png",
	StaticContent: resourceGUIf2PngData,
}
